version: "3"

services:
  node:
    build: .
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8080"
    ports: # use if it is necessary to expose the container to the host machine
      - "8080:80"
