version: "3"

services:
  node:
    image: node:20
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    command: /bin/bash -c "npm install && npm run build"
